<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 *
 */
/** @var \Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $this->helper(\Magento\Customer\Helper\Address::class);
$directoryHelper = $this->helper(\Healthyvibes\Directory\Helper\Data::class);
$address = $directoryHelper->loadCustomerAddress($block->getAddress()->getId());
$requiredAttributesPrechecked = $block->getData('required_attributes_prechecked');
$autofilledFlag = $directoryHelper->isZipCodeAutofilled();
?>
<form class="form-address-edit" action="<?= $block->escapeUrl($block->getSaveUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>"/>
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>"/>
        <?= $block->getNameBlockHtml() ?>
        <?php if ($addressHelper->isAttributeVisible('company')) : ?>
            <div class="field company <?php if (in_array('company', $requiredAttributesPrechecked)) :
                ?>required<?php endif; ?>">
                <label class="label" for="company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
                <div class="control">
                    <input type="text" name="company" id="company" title="<?= $block->escapeHtmlAttr(__('Company')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCompany()) ?>" class="input-text <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('company')) ?>"/>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($addressHelper->isAttributeVisible('telephone')) : ?>
            <div class="field telephone <?php if (in_array('telephone', $requiredAttributesPrechecked)) :
                ?>required<?php endif; ?>">
                <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input type="text" placeholder="<?= $block->escapeHtml(__('Phone Number')) ?>" name="telephone" value="<?= $block->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('telephone') ?>" id="telephone"/>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($addressHelper->isAttributeVisible('fax')) : ?>
            <div class="field fax">
                <label class="label" for="fax"><span><?= $block->escapeHtml(__('Fax')) ?></span></label>
                <div class="control">
                    <input type="text" name="fax" id="fax" title="<?= $block->escapeHtmlAttr(__('Fax')) ?>" value="<?= $block->escapeHtmlAttr($block->getAddress()->getFax()) ?>" class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('fax') ?>"/>
                </div>
            </div>
        <?php endif; ?>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend><br>
        <?php if ($addressHelper->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span></label>
                <div class="control">
                    <input type="text" name="vat_id" value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('vat_id') ?>" id="vat_id"/>
                </div>
            </div>
        <?php endif; ?>
        <div class="field region required">
            <label class="label" for="region_id"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" <?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"  title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region') ?>"<?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
            <div class="control">
                <select id="city_id" name="city_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="validate-select region_id" <?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a city or district.')) ?></option>
                </select>
                <input placeholder="<?= $block->escapeHtml(__('City')) ?>" type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city') ?>" id="city"/>
            </div>
        </div>

        <?php
        $wardId = $address->getWardId();
        $ward = $address->getWard();
        $cityId = $address->getCityId();
        if (!$cityId) {
            $cityId = $directoryHelper->getCityIdByRegionName((int)$block->getRegionId(), $block->getAddress()->getCity());
        }
        $wards = [];
        if($cityId) {
            $wards = $directoryHelper->getAllWard($cityId);
        }
        ?>
        <div class="field ward required">
            <label class="label" for="ward"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('ward') ?></span></label>
            <div class="control">
                <input type="hidden" name="ward" id="ward_txt" value="<?php echo $ward; ?>" />
                <select id="fward" name="ward_id" class="required-entry">
                    <option value=""><?php echo __('Please select a ward'); ?></option>
                    <?php
                    if(count($wards)){
                        foreach($wards as $ward):?>
                            <option class="opt" <?php echo (($wardId == $ward->getWardId())? 'selected="selected"' : '') ?>
                                    data-city_id="<?php echo $ward->getCityId(); ?>"
                                    value="<?php echo $ward->getWardId(); ?>"><?php echo $ward->getDefaultName(); ?></option>
                        <?php
                        endforeach;
                    }
                    ?>
                </select>
            </div>
        </div>
        <?php $_streetValidationClass = $addressHelper->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
            <div class="control">
                <input type="text" name="street[]" placeholder="<?= $block->escapeHtmlAttr(__('Enter the street address')) ?>" value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="street_1" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>"/>
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $addressHelper->getStreetLines(); $_i <= $_n; $_i++) : ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $_i)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i)) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Enter the street address')) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>"/>
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
            <div class="control">
                <?php if ($autofilledFlag): ?>
                    <input type="text" placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" readonly name="postcode" value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode') ?>"/>
                <?php else: ?>
                    <input type="text" placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" name="postcode" value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode') ?>"/>
                <?php endif; ?>
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_address_user_attributes'); ?>
        <?php if ($userDefinedAttributes) :?>
            <?= $userDefinedAttributes->setShowContainer(false)->toHtml() ?>
        <?php endif;?>
        <?php if ($block->isDefaultBilling()) : ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("This is your default billing address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()) : ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox"/>
                <label class="label" for="primary_billing"><span><?= $block->escapeHtml(__('Use as my default billing address')) ?></span></label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_billing" value="1"/>
        <?php endif; ?>
        <?php if ($block->isDefaultShipping()) : ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("This is your default shipping address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()) : ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox"/>
                <label class="label" for="primary_shipping"><span><?= $block->escapeHtml(__('Use as my default shipping address')) ?></span></label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_shipping" value="1"/>
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" data-action="save-address" title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $block->escapeHtml(__('Save and update')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        },
        "#region_id": {
            "cityUpdater": {
                "isMultipleCountriesAllowed": false,
                "optionalCityAllowed": <?= /* @noEscape need to do config*/ ($block->getConfig('general/city/display_all') ? 'true' : 'false') ?>,
                "countryId": "#country",
                "cityListId": "#city_id",
                "cityInputId": "#city",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "cityJson": <?= /* @noEscape */ $directoryHelper->getCityJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getRegionId() ?>",
                "defaultCity": <?= /* @noEscape */ $cityId ?>,
                "autofilledZipcode": <?= /* @noEscape */ $directoryHelper->isZipCodeAutofilled() ? 'true' : 'false' ?>
            }
        }
    }
</script>
<script type="text/javascript">
    require([
        'jquery'
    ], function($){
        $(document).ready(function(){

            $(document).on("change", "#city_id", function(){
                var _cityTxt = $(this).find("option:selected").text();
                $("#city").val(_cityTxt);
                var _cityId = $(this).val();
                var _cWardId = '<?php echo $wardId; ?>';
                $("#fward option.opt").addClass("hidden");
                $("#fward").val("");
                $("#ward_txt").val("");
                $.ajax({
                    dataType : 'html',
                    showLoader: false,
                    url : '<?php echo $directoryHelper->getAjaxWardUrl() ?>?city_id='+_cityId+'&ward_id='+_cWardId,
                    success : function(data){
                        $("#fward").html(data);
                    }
                });
            });
            $(document).on("change", "#fward", function(){
                var _wardTxt = $(this).find("option:selected").text();
                $("#ward_txt").val(_wardTxt);
            });
        });
    });
</script>
