<?php
/**
 * Solwin Infotech
 * Solwin ScrolltoTop Extension
 *
 * @category   Solwin
 * @package    Solwin_ScrolltoTop
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/
 */
?>
<?php
$enable = $block->getConfig('scrollsection/scrollgroup/active');
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$moduleManager = $objectManager->get('\Magento\Framework\Module\Manager');
$moduleEnabled = $moduleManager->isEnabled('Solwin_ScrolltoTop');
if ($enable && $moduleEnabled) {
    $imghtml = $text = $img = $path = '';

    $bgclr = $block->getConfig('scrollsection/scrollgroup/bgclr');
    $bgHoverClr = $block->getConfig('scrollsection/scrollgroup/bghoverclr');
    $textclr = $block->getConfig('scrollsection/scrollgroup/textclr');
    $textHoverClr = $block->getConfig('scrollsection/scrollgroup/texthoverclr');
    $display = $block->getConfig('scrollsection/scrollgroup/display');
    $text = $block->getConfig('scrollsection/scrollgroup/link_text');
    $img = $block->getConfig('scrollsection/scrollgroup/link_image');
    $hoverImg = $block->getConfig('scrollsection/scrollgroup/link_hover_image');
    $position = $block->getConfig('scrollsection/scrollgroup/position');
    if ($img != '') {
        $path = $block->getBaseUrl() . 'pub/media/scrolltotop/' . $img;
        $hover_path = $block->getBaseUrl() . 'pub/media/scrolltotop/' . $hoverImg;
        $imghtml = '<img class="scroll-img default-img" src="' . $path . '" alt="top" />'
                . '<img class="scroll-img hover-img" src="' . $hover_path . '" alt="top-hover" />';
    }
    ?>
    <div id="scroll-to-top">
        <a class="scrollup" href="#" title="<?= $block->escapeHtml(__('Scroll to Top')) ?>" style="<?php if ($position == 1) { ?> right:10px; <?php } else { ?> left:10px; <?php } ?> ">
            <?php
            if ($display == 2 || $display == 3) {
                echo $imghtml;
            }
            ?>
            <?php if ($display == 1 || $display == 3) { ?>
            <span style="<?php if ($display == 3) { ?> padding: 0 0 5px;display: block; <?php } else { ?> float: left;padding: 10px 0;text-align: center;width: 100%; <?php } ?>"><?= $block->escapeHtml(__($text)) ?></span>
            <?php } ?>
        </a>
    </div>
    <?php
}
?>
<a id="button-scroll-to-top"></a>
<style>
    .scrollup:visited, .scrollup:active {
        color: #<?= /* @noEscape */ $textclr ?> !important;
    }
    .scrollup{
        color: #<?= /* @noEscape */ $textclr ?> !important;
        background-color: #<?= /* @noEscape */ $bgclr ?> !important;
        border-color: #<?= /* @noEscape */ $bgclr ?> !important;
    }

    .scrollup:hover {
        color: #<?= /* @noEscape */ $textHoverClr  ?> !important;
        background-color: #<?= /* @noEscape */ $bgHoverClr ?> !important;
        border-color: #<?= /* @noEscape */ $bgHoverClr ?> !important;
    }
    #button-scroll-to-top {
        display: inline-block;
        background-color: #FF9800;
        width: 50px;
        height: 50px;
        text-align: center;
        border-radius: 4px;
        position: fixed;
        bottom: 30px;
        right: 30px;
        transition: background-color .3s,
        opacity .5s, visibility .5s;
        opacity: 0;
        visibility: hidden;
        z-index: 1000;
    }
    #button-scroll-to-top::after {
        content: "\f077";
        font-family: FontAwesome;
        font-weight: normal;
        font-style: normal;
        font-size: 2em;
        line-height: 50px;
        color: #fff;
    }
    #button-scroll-to-top:hover {
        cursor: pointer;
        background-color: #333;
    }
    #button-scroll-to-top:active {
        background-color: #555;
    }
    #button-scroll-to-top.show {
        opacity: 1;
        visibility: visible;
    }
</style>
<script>
    require([
        'jquery'
    ], function($){
        var btn = $('#button-scroll-to-top');

        $(window).scroll(function() {
            if ($(window).scrollTop() > 300) {
                btn.addClass('show');
            } else {
                btn.removeClass('show');
            }
        });

        btn.on('click', function(e) {
            e.preventDefault();
            $('html, body').animate({scrollTop:0}, '300');
        });
    })
</script>
